name: CI/CD Pipeline

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          # Add your test commands here, e.g., pytest
          pytest

      - name: Build application
        run: |
          # This is usually not required for Python Flask apps, but include if needed
          echo "Building Flask application..."

      - name: Deploy to server
        run: |
          echo "Deploying to server..."
          # Replace this with actual deployment commands, e.g., SCP to copy files, etc.
          scp -r ./* user@your-server:/path/to/deploy
          ssh user@your-server 'cd /path/to/deploy && sudo systemctl restart your-flask-app'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
